export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const SEQUELIZE = 'SEQUELIZE';



export const USER_REPOSITORY = 'USER_REPOSITORY';
export const SECTOR_REPOSITORY = 'SECTOR_REPOSITORY';
export const STOCK_EXCHANGE_REPOSITORY = 'STOCK_EXCHANGE_REPOSITORY';
export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const DAILY_PRICE_REPOSITORY = 'DAILY_PRICE_REPOSITORY';